name: flutter_projects
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^3.1.0
  share_plus: ^11.0.0
  flutter_branch_sdk: ^8.2.0
  blur: ^3.1.0
  wakelock_plus: ^1.3.2
  quick_actions: ^1.1.0
  flutter_plugin_android_lifecycle: ^2.0.28
  interactive_media_ads: ^0.2.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter